# Generated by Django 5.1.4 on 2025-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('finance', 'Finance'), ('registrar', 'Registrar')], max_length=20)),
            ],
            options={
                'verbose_name': 'Add User',
                'verbose_name_plural': 'Add Users',
            },
        ),
    ]
