# Generated by Django 5.1.4 on 2025-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
