# Generated by Django 5.1.4 on 2025-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adduser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('date_requested', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
