# Generated by Django 5.1.4 on 2025-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_documentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
