# Generated by Django 5.1.4 on 2025-09-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
    ]
