# Generated by Django 5.1.4 on 2025-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='lrn',
            field=models.CharField(max_length=12),
        ),
    ]
