# Generated by Django 5.1.4 on 2025-09-05 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentrecord_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='lrn',
            field=models.CharField(help_text='Enter 12-digit LRN (numbers only).', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,12}$', message='LRN must be 1–12 digits only.')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
