# Generated by Django 5.1.4 on 2025-09-05 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentrecord_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\-]+$', message='This field can only contain letters, spaces, and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\-]+$', message='This field can only contain letters, spaces, and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='lrn',
            field=models.CharField(help_text='Enter exactly 12 digits for the LRN.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='LRN must be exactly 12 digits (numbers only).')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\-]+$', message='This field can only contain letters, spaces, and hyphens.')]),
        ),
    ]
