# Generated by Django 5.1.4 on 2025-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_studentrecord_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='lrn',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
